name: MERN CI

on: 
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:6.0
        ports: ['27017:27017']
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          echo "Listing backend files:"
          ls -la
          node seedTaskData.js  

  test:
    runs-on: ubuntu-latest
    needs: mongo-init
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
            
      - name: Install Dependencies for backend
        working-directory: ./backend
        run: npm install
          
      - name: Running Backend Tests
        working-directory: ./backend
        run: npm test
